# Generated by Django 3.0 on 2019-07-30 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='分类名称')),
            ],
            options={
                'verbose_name': '资讯类别',
                'verbose_name_plural': '资讯类别',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='文章内容')),
                ('date', models.DateTimeField(verbose_name='发布时间')),
                ('show', models.BooleanField(verbose_name='是否显示')),
                ('news_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_app.NewsClass', verbose_name='文章分类')),
            ],
            options={
                'verbose_name': '资讯',
                'verbose_name_plural': '资讯',
            },
        ),
    ]
